version: "3"
name: rhythm
services:
  api:
    restart: unless-stopped
    build:
      context: .
    expose:
      - 5001
    environment:
      - PORT=5001
    networks:
      bioloop_network:
        ipv4_address: 172.19.0.4

  # sudo docker compose -f "docker-compose-dev.yml" run --rm mongobackup
  mongobackup:
    image: mongo:5
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - PROJ_NAME=${COMPOSE_PROJECT_NAME}
    volumes:
      - /opt/sca/postgres_backups:/backup
    command: >
      bash -c 'mongodump --uri="mongodb://$MONGO_USER:$MONGO_PASS@$MONGO_HOST:$MONGO_PORT/$MONGO_DB?authSource=$MONGO_AUTH_SOURCE" --archive=/backup/$PROJ_NAME.mongo.$(date +%F).gz --gzip'


networks:
  bioloop_network:
    external: true