version: "3"
services:
  queue:
    # https://hub.docker.com/_/rabbitmq/
    container_name: rhythm_queue
    # includes web gui ?
    image: rabbitmq:3-management
    # image: rabbitmq:3
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - ./db/queue/data/:/var/lib/rabbitmq/
      # - ./db/queue/log/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=myvhost

  mongo:
    # https://hub.docker.com/_/mongo
    container_name: rhythm_mongo
    image: mongo:5
    ports:
      # helpful for using a GUI client like compass for troubleshooting
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db/db_mongo:/data/db
      # for importing database files
      - ./db/mongodump:/opt/sca/app/mongodump

  # init-db:
  #   container_name: rhythm_mongo_init_db
  #   image: mongo:5
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./mongo:/scripts
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: mydb
  #   command: ["bash", "-c", "mongo mongo:27017/mydb -u root -p example /scripts/init-db.sh"]
