version: "3"
name: rhythm
services:
  api:
    restart: unless-stopped
    build:
      context: .
    expose:
      - 5001
    environment:
      - PORT=5001
    networks:
      bioloop_network:
        ipv4_address: 172.19.0.4

networks:
  bioloop_network:
    external: true