version: "3"
name: rhythm
services:
  api:
    restart: unless-stopped
    build:
      context: .
    expose:
      - 5001
    ports:
      - 127.0.0.1:5001:5001
    environment:
      - PORT=5001
    depends_on:
      - queue
      - mongo
    networks:
      rhythm_network:
        ipv4_address: 172.19.1.2
      rhythm_bioloop_bridge:
        ipv4_address: 172.19.2.2

  queue:
    # https://hub.docker.com/_/rabbitmq/
    # includes web gui ?
    image: rabbitmq:3-management
    # image: rabbitmq:3
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - ./db/queue/data/:/var/lib/rabbitmq/:z
      # - ./db/queue/log/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${QUEUE_USER}
      - RABBITMQ_DEFAULT_PASS=${QUEUE_PASS}
      - RABBITMQ_DEFAULT_VHOST=${QUEUE_VHOST}
    networks:
      rhythm_network:
        ipv4_address: 172.19.1.3

  mongo:
    # https://hub.docker.com/_/mongo
    image: docker.io/library/mongo:5
    ports:
      # helpful for using a GUI client like compass for troubleshooting
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db/db_mongo:/data/db:z
      # for importing database files
      - ./db/mongodump:/opt/sca/app/mongodump:z
    networks:
      rhythm_network:
        ipv4_address: 172.19.1.4

# sudo docker compose -f "docker-compose-prod.yml" run --rm mongobackup
  mongobackup:
    image: docker.io/library/mongo:5
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - PROJ_NAME=${COMPOSE_PROJECT_NAME}
    volumes:
      - /opt/sca/db_backups:/backup:z
    command: >
      bash -c 'mongodump --uri="mongodb://$MONGO_USER:$MONGO_PASS@$MONGO_HOST:$MONGO_PORT/$MONGO_DB?authSource=$MONGO_AUTH_SOURCE" --archive=/backup/rhythm.mongo.$(date +%F).gz --gzip'
    networks:
      rhythm_network:
        ipv4_address: 172.19.1.5

networks:
  rhythm_network:
    name: rhythm-network
    ipam:
      config:
        - subnet: 172.19.1.0/24
  rhythm_bioloop_bridge:
    name: rhythm-bioloop-bridge
    ipam:
      config:
        - subnet: 172.19.2.0/24
